#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"
APP_ROOT="$DOKKU_ROOT/$APP"

GIT_VERSION=`cd $APP_ROOT && git describe --tags --always`

if [[ -f "$APP_ROOT/ENV" ]]; then
  dokku config:set $APP 'GIT_VERSION=$GIT_VERSION'
fi
